### ISSUE TITLE
ReferenceError thrown on assigning to undeclared global in script file (as if in strict mode/module)

### ISSUE THREAD

**Issue by harig** [quickjs-ng/quickjs#634] opened 2024-10-28 10:19 UTC
After 8cd59bf7c439e337 qjs throws ReferenceError for an undeclared global assignment in a script file. 

Consider a js file with this code
`a=1;console.log(typeof a);`
This used to output "number" earlier but now without `--script` argument before the file path, an error is thrown.
`ReferenceError: a is not defined`
It seems the file is considered to be a module and strict mode is enforced if `--script` is not specified.

Shouldn't this work as it did before (raising the error only if strict mode is specified) ?

**Comment by saghul** [comment] 2024-10-28 10:23
Yes, that would be a side effect of https://github.com/quickjs-ng/quickjs/pull/610

Honestly, I think thr current approach is better than before, as in, use modules by default unless we can detect otherwise.

@bnoordhuis I wonder if it would make sense to make the test "heavier" by checking twice, once as a script, once as a module and if both succeed, use module, otherwise pick the correct one. WDYT?

**Comment by bnoordhuis** [comment] 2024-10-28 11:38
That won't work. `a=1;console.log(typeof a);` is not obviously a classic script or a module, it parses fine either way. It's only when you run it that the difference becomes visible, and even then, it'd still run okay as a module if `globalThis.a` exists.

Editorial: that's why I wrote in the commit log that the premise of auto-detection is wrong - no matter what choices you make, it's always going to be wrong some of the time.

**Comment by saghul** [comment] 2024-10-28 11:44
Ah, right. Shall we close this then?

**Comment by bnoordhuis** [comment] 2024-10-28 11:53
Yes. Working as intended / as well as possible.

**Closed as not planned by bnoordhuis** 2024-10-28 11:53 UTC
